### ISSUE TITLE
Shorten the firecracker unix socket path

### ISSUE THREAD

**Issue by haikuoliu** [firecracker-microvm/firecracker-containerd#264]
Firecracker containerd constructs the firecracker socket path using pattern `/var/run/firecracker-containerd/$NAMESPACE/$VMID/firecracker.sock`, however, Linux has a limit on the length of socket path, that means if I am using uuid for both namespace and vmid, the firecracker socket path will be 122 characters long which is beyond the limit. 

Containerd used to have this problem to create shim socket, they fixed the issue in this [PR](https://github.com/containerd/containerd/pull/3046) where they do sha256 on the path, is it possible for firecracker containerd to do the same?

Thanks,
Haikuo

**Comment by sipsma** [comment]
We definitely need to address this, but unfortunately I don't believe we'll be able to do what containerd did with the shim socket path. The difference is containerd shims use abstract unix sockets, which don't actually exist on the filesystem (which is confusing because it's still specified with a "path", but the path is really just an id unique within the network namespace the abstract socket lives in).

Firecracker uses normal unix sockets, not abstract, so we can't solve the problem by just taking a hash. What I believe we can do is specify the socket path as a relative one. The shim process and Firecracker VMM process will be in the `$VMID` directory, so I think they can get away with just specifying `./firecracker.sock`. They should never change working dir once started up, so this should be safe and well under the character limit.
