### ISSUE TITLE
Support for containerd-shim-runc-v2

### ISSUE THREAD

**Issue by andrewrynhard** [firecracker-microvm/firecracker-containerd#385]
We would love to run this, but need containerd-shim-runc-v2. Has this been considered?

**Comment by IRCody** [comment]
Inside the VM we are using the runc-v2 shim [here](https://github.com/firecracker-microvm/firecracker-containerd/blob/master/agent/service.go#L28). Outside we are using the v2 api to create our own shim that calls into firecracker.

Can you be more specific about what is missing in order to make it suitable for you?

**Comment by andrewrynhard** [comment]
Sorry, this just might be misunderstanding. Reading this again:

> An agent running inside the microVM, which invokes runC via containerd's containerd-shim-runc-v1 to create standard Linux containers inside the microVM.

and I failed to realize `containerd-shim-runc-v1` was _inside_ the microVM.

**Comment by IRCody** [comment]
Let us know if you find other issues that block your use of firecracker-containerd.
