### ISSUE TITLE
Supported gRPC version is too old

### ISSUE THREAD

**Issue by ustiugov** [firecracker-microvm/firecracker-containerd#521]
Dear maintainers,

Please consider upgrading the version of gRPC that is currently v1.27. For example, recent protoc v3.11 (which we are currently using and the latest is already v3.17) requires gRPC >=v1.32 (latest is v1.38).

https://github.com/firecracker-microvm/firecracker-containerd/blob/c2323bc71886b3abfefd9afa53244740f70db0b8/go.mod#L39

@boramalper can provide more details upon request

**Comment by RoyceDavison** [comment]
I just took a quick look into it and found out that the latest grpc v1.38 uses both modules: [golang/protobuf v1.4.3](https://github.com/grpc/grpc-go/blob/d9eb12feed7a0f45d4acbf478e83171f4c00210a/go.mod#L10) and google.golang.org/protobuf v1.25.0. 
emm...Is there any breaking api change?

**Comment by kzys** [comment]
firecracker-containerd is currently using containerd 1.5.x, which is using the old gRPC due to other dependencies.

containerd has upgraded gRPC recently but it hasn't been released and containerd team generally don't backport dependency changes unless it has security fixes.

So we would wait containerd's 1.6 release regarding gRPC upgrade.

**Comment by henry118** [comment]
We have upgraded gRPC to [1.38](https://github.com/containerd/containerd/pull/6660) recently when upgrading to containerd 1.6.

**Comment by henry118** [comment]
I'll mark this issue closed for now. Feel free to reopen/cut new ticket for anything else needed.
