### ISSUE TITLE
Support multiple containers in a single Firecracker microVM

### ISSUE THREAD

**Issue by samuelkarp** [firecracker-microvm/firecracker-containerd#74]
We'd like to support running multiple containers in a single Firecracker microVM, to support use-cases like running a Kubernetes pod (with its requirements around shared namespaces) in a microVM.

**Comment by samuelkarp** [comment]
Some things that we'll need to figure out:

* vsock port assignment for container stdio streams
* mount location assignment for container rootfs
* agent<->shim relationship (one-to-one, one-to-many)
* runtime<->VMM relationship (one-to-one, one-to-many, many-to-one)
* VM lifecycle management

**Comment by IRCody** [comment]
>vsock port assignment for container stdio streams

I think it might be worth writing down what is happening now so we can discuss possible solutions for this. Currently there are 3 vsock ports that are statically defined under internal.Std{in,out,err}Port. Because it's static there doesn't need to be any sort of communication re: what port to use between the runtime and the agent. This obviously won't work for multiple containers in a VM.

Whatever we choose for this is probably very related to the solution for exec processes, see #77.

**Comment by mxpv** [comment]
Done in https://github.com/firecracker-microvm/firecracker-containerd/pull/164 https://github.com/firecracker-microvm/firecracker-containerd/pull/154 https://github.com/firecracker-microvm/firecracker-containerd/issues/159
