### ISSUE TITLE
Don't share a mutable rootfs with all microVMs

### ISSUE THREAD

**Issue by samuelkarp** [firecracker-microvm/firecracker-containerd#75]
We currently use the same rootfs image for all microVMs, and it is mounted read/write.  We need to prevent multiple microVMs from mutating it, or present a separate copy of the image to each microVM.

**Comment by nmeyerhans** [comment]
Two immediate options come to mind for this, both of which are inspired by container (and/or live-cd) behavior.

**Option 1:** Support is implemented within the MicroVM: The root backing store is attached read-only, and a read/write layer (possibly just a ramdisk) is overlayed  to create a writable root filesystem. An advantage here is that the backing store can be squashfs, which will reduce the on-disk footprint. It also requires minimal host setup.

**Option 2:** Support is implemented using LVM thin-pools. The common content is stored as a logical volume, and each VM is given a private snapshot of the volume. This is conceptually similar to the way that our [devmapper snapshotter](https://github.com/firecracker-microvm/firecracker-containerd/tree/master/snapshotter/devmapper) works.

I think either of these options can work. Option 1 may be preferable initially because it requires less setup. All required functionality can be bundled into the microVM image.

**Comment by mcastelino** [comment]
@samuelkarp @nmeyerhans if the host fs supported `reflink` would you consider that secure enough.

**Comment by samuelkarp** [comment]
@nmeyerhans and I discussed this over lunch today.  I think there's another option that might be simpler and provides the guarantees that we want (host-based components are protected against mutation from something inside the microVM).  So, adding to Noah's list:

**Option 3:** This is the same as Option 1 above (read-only attachment and a read/write overlay within the microVM if necessary) combined with creating a per-microVM overlay outside microVM to hold all of the host-based components that we expect (kernel binary, rootfs image, and the firecracker and jailer binaries).  We expect (but need to validate) that Firecracker will open with `O_RDONLY` when we create a read-only attachment, which will eliminate the need for an overlay copy-up operation (and save both the time and space necessary for such an operation).  This should also play nicely with the jailer, as the jailer already needs a private root (mount namespace + pivot_root) anyway.

**Comment by nmeyerhans** [comment]
The image created in #153 can be safely attached to multiple VMs, with a per-VM read/write overlay in use.
